// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUa8--WpYXFHKXjsfUCyZla_8QbVeAm4U',
    appId: '1:747754990384:web:58c2fda6f42fd2982ab6f5',
    messagingSenderId: '747754990384',
    projectId: 'ecommerce-48e06',
    authDomain: 'ecommerce-48e06.firebaseapp.com',
    storageBucket: 'ecommerce-48e06.appspot.com',
    measurementId: 'G-C2QJXVEJR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVZgyC9_2e7diiyDiDaKmue3N8vqORosc',
    appId: '1:747754990384:android:1d360a956372b6b42ab6f5',
    messagingSenderId: '747754990384',
    projectId: 'ecommerce-48e06',
    storageBucket: 'ecommerce-48e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnbeZhS05NQKSL6_-GAG1nnTf_lnq8YjY',
    appId: '1:747754990384:ios:ef60ca1f7b5b27922ab6f5',
    messagingSenderId: '747754990384',
    projectId: 'ecommerce-48e06',
    storageBucket: 'ecommerce-48e06.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnbeZhS05NQKSL6_-GAG1nnTf_lnq8YjY',
    appId: '1:747754990384:ios:d11232835238fc492ab6f5',
    messagingSenderId: '747754990384',
    projectId: 'ecommerce-48e06',
    storageBucket: 'ecommerce-48e06.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
